% Toolchain validation: openEMS reference patch (known resonance ~2.4 GHz)
addpath('/opt/openEMS/share/openEMS/matlab'); addpath('/opt/openEMS/share/CSXCAD/matlab');
physical_constants; unit = 1e-3;
patch.width=32; patch.length=40;
substrate.epsR=3.38; substrate.kappa=1e-3*2*pi*2.45e9*EPS0*substrate.epsR;
substrate.width=60; substrate.length=60; substrate.thickness=1.524; substrate.cells=4;
feed.pos=-6; feed.R=50; SimBox=[200 200 150];
f0=2e9; fc=1e9;
FDTD=InitFDTD('NrTs',30000); FDTD=SetGaussExcite(FDTD,f0,fc);
FDTD=SetBoundaryCond(FDTD,{'MUR','MUR','MUR','MUR','MUR','MUR'});
CSX=InitCSX();
mesh.x=[-SimBox(1)/2 SimBox(1)/2]; mesh.y=[-SimBox(2)/2 SimBox(2)/2]; mesh.z=[-SimBox(3)/3 SimBox(3)*2/3];
CSX=AddMetal(CSX,'patch');
CSX=AddBox(CSX,'patch',10,[-patch.width/2 -patch.length/2 substrate.thickness],[patch.width/2 patch.length/2 substrate.thickness]);
CSX=AddMaterial(CSX,'substrate');
CSX=SetMaterialProperty(CSX,'substrate','Epsilon',substrate.epsR,'Kappa',substrate.kappa);
CSX=AddBox(CSX,'substrate',0,[-substrate.width/2 -substrate.length/2 0],[substrate.width/2 substrate.length/2 substrate.thickness]);
mesh.z=[linspace(0,substrate.thickness,substrate.cells+1) mesh.z];
CSX=AddMetal(CSX,'gnd');
CSX=AddBox(CSX,'gnd',10,[-substrate.width/2 -substrate.length/2 0],[substrate.width/2 substrate.length/2 0]);
[CSX port]=AddLumpedPort(CSX,5,1,feed.R,[feed.pos 0 0],[feed.pos 0 substrate.thickness],[0 0 1],true);
mesh=DetectEdges(CSX,mesh,'ExcludeProperty','patch');
mesh=DetectEdges(CSX,mesh,'SetProperty','patch','2D_Metal_Edge_Res',c0/(f0+fc)/unit/50);
mesh=SmoothMesh(mesh,c0/(f0+fc)/unit/20);
CSX=DefineRectGrid(CSX,unit,mesh);
Sim_Path='tmp_ref'; Sim_CSX='ref.xml';
CleanupSimPath(Sim_Path); WriteOpenEMS([Sim_Path '/' Sim_CSX],FDTD,CSX);
RunOpenEMS(Sim_Path,Sim_CSX,'--numThreads=4');
freq=linspace(1e9,3e9,501); port=calcPort(port,Sim_Path,freq);
s11=20*log10(abs(port.uf.ref./port.uf.inc));
[m,i]=min(s11);
printf('\n=== VALIDATION: f_res = %.3f GHz, S11 = %.2f dB (expected ~2.4 GHz) ===\n',freq(i)/1e9,m);
